services:
  gitlab-ce:
    container_name: gitlab-ce
    image: gitlab/gitlab-ce:16.7.9-ce.0
    restart: always
    hostname: 'gitlab.hdb.fr'
    ports:
      - 9080:80 # port web (http)
      - 9043:443 # port sécurisé (https)
      - 9022:22  # connexion ssh
    volumes:
      - './gitlab-data/config:/etc/gitlab'
      - './gitlab-data/logs:/var/log/gitlab'
      - './gitlab-data/data:/var/opt/gitlab'
    networks:
      - applications-networks
    shm_size: '256m'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
networks:
  applications-networks:
    name: applications-networks
    external: true